version: '3.7'

services:

  validator:
    build:
      context: .
      dockerfile: Dockerfile
    #image: "cwrc/cwrc-validator:latest"
    #volumes:
    #  - ./container_volumes/validator/:/usr/local/tomcat/logs
